version: "3"
services:
  indexoor-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: indexoor-web
    image: indexoor-web
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    volumes:
      - ./indexoor:/home/worker/indexoor
    command: ["gunicorn", "--config", "gunicorn.conf.py", "--reload", "web:app"]

  indexoor-db:
    container_name: indexoor-db
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
