version: "3"
services:
  indexoor-web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: indexoor-web
    image: indexoor-web
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    volumes:
      - ./indexoor:/home/worker/indexoor
